### ISSUE TITLE
Doesn't render anything inside single backtics.

### ISSUE THREAD

**Issue by Toady00** [kentaro-m/blackfriday-confluence#10]
When rendering anything inside backtics, instead of getting `foo` you get nothing.

**Comment by kentaro-m** [comment]
Hi, @Toady00. Thank you for reporting the issue.
I forgot to implement it.
When single backticks were included, it was necessary to render two curly braces.

```
e.g. this is `foo` => this is {{foo}}
```
[Quick Reference Guide for the Confluence Editor - Confluence 5.6 - Atlassian Documentation](https://confluence.atlassian.com/display/CONF56/Quick+Reference+Guide+for+the+Confluence+Editor)

**Comment by kentaro-m** [comment]
Fixed this Issue #11
